customhost = "employee.cjj1z4ah4uho.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "khuweeming-bucket"
customregion = "us-east-1"
